Update fIX_bOOK_cONTROL.java
CSU-GagaCoder/assignment-1 pull request #13
Opened 2020-08-19 07:16 UTC by chandrika-katikam

2020-08-20 23:38 UTC, ttawan commented on src/library/fixbook/fIX_bOOK_cONTROL.java
> +	public void SeT_uI(FixBookUI uI) {
Change to ```setUI``` not SeT_UI

2020-08-20 23:38 UTC, ttawan commented on src/library/fixbook/fIX_bOOK_cONTROL.java
> +	public void SeT_uI(FixBookUI uI) {
```public void setUI(FixBookUI UI)```

2020-08-20 23:39 UTC, ttawan commented on src/library/fixbook/fIX_bOOK_cONTROL.java
> +		this.Ui = uI;
```this.UI = UI```

2020-08-24 11:18 UTC, parneetbatra commented
all good

2020-08-25 07:55 UTC, aatish-rajkarnikar approved these changes

2020-08-25 11:01 UTC, parneetbatra commented
all good

2020-08-25 11:02 UTC, parneetbatra approved these changes

2020-08-27 14:32 UTC, ttawan commented on src/library/fixbook/fIX_bOOK_cONTROL.java
> +	public void SeT_uI(FixBookUI uI) {
Change to ```set_UI```

2020-08-27 14:32 UTC, ttawan requested changes

2020-08-27 14:32 UTC, ttawan commented on src/library/fixbook/fIX_bOOK_cONTROL.java
> +		this.Ui = uI;
Change to ```this.UI```

2020-08-27 14:36 UTC, merged