Merge to master
CSU-GagaCoder/assignment-1 pull request #19
Opened 2020-08-24 12:06 UTC by parneetbatra

2020-08-25 07:57 UTC, aatish-rajkarnikar approved these changes

2020-08-26 09:52 UTC, parneetbatra commented
@ttawan and @chandrika-katikam please review my changes and approve. Thanks

2020-08-26 09:54 UTC, ttawan requested changes
Please see comments in the file

2020-08-26 09:54 UTC, ttawan commented on src/library/Main.java
> +				output("\n" + SDF.format(CAL.gEt_DaTe())); // gEt_DaTe change to getDate
Maybe change this to CAL.getDate() @parneetbatra

2020-08-26 10:15 UTC, parneetbatra commented on src/library/Main.java
> +				output("\n" + SDF.format(CAL.gEt_DaTe())); // gEt_DaTe change to getDate
Thanks for the feedback. Changed to CAL.getDate()

2020-08-27 00:03 UTC, ttawan commented on src/library/Main.java
> +				// output("\n" + SDF.format(CAL.gEt_DaTe()));
Maybe remove this line? 
```
				// output("\n" + SDF.format(CAL.gEt_DaTe()));
```

2020-08-27 00:05 UTC, ttawan requested changes
small changes. Maybe remove print log?

2020-08-27 12:30 UTC, merged