Commented on code
CSU-GagaCoder/assignment-1 pull request #25
Opened 2020-08-27 22:08 UTC by parneetbatra

Commented on code

2020-08-27 22:36 UTC, parneetbatra commented
@aatish-rajkarnikar @chandrika-katikam @ttawan I commented code and fix some issue. Please approve, Thanks.

2020-08-27 22:51 UTC, aatish-rajkarnikar approved these changes
Everything is good!

2020-08-28 01:25 UTC, ttawan requested changes
Please remove all links from readme

2020-08-28 01:25 UTC, ttawan commented on README.md
> +#### Pull requests
Why did you added those links to README ?

2020-08-28 01:46 UTC, parneetbatra commented on README.md
> +#### Pull requests
Removed links

2020-08-28 02:06 UTC, merged